Problem Statement : Data Analytics III 
1. Implement Simple Naïve Bayes classification algorithm using Python/R on iris.csv dataset. 
2. Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate, Precision, Recall on 
the given dataset. 

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix , accuracy_score, precision_score, recall_score, f1_score
from sklearn.naive_bayes import GaussianNB

In [ ]:
df= pd.read_csv("/content/Iris (1).csv")

In [ ]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0      1            5.1           3.5            1.4           0.2     Iris-setosa
1      2            4.9           3.0            1.4           0.2     Iris-setosa
2      3            4.7           3.2            1.3           0.2     Iris-setosa
3      4            4.6           3.1            1.5           0.2     Iris-setosa
4      5            5.0           3.6            1.4           0.2     Iris-setosa
..   ...            ...           ...            ...           ...             ...
145  146            6.7           3.0            5.2           2.3  Iris-virginica
146  147            6.3           2.5            5.0           1.9  Iris-virginica
147  148            6.5           3.0            5.2           2.0  Iris-virginica
148  149            6.2           3.4            5.4           2.3  Iris-virginica
149  150            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 6 columns]

In [ ]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
#split dataset
X= df.drop("Species", axis=1)
y= df["Species"]

In [ ]:
X

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [ ]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [ ]:
# Splitting the dataset into training and test sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
# Initializing and training the Naïve Bayes classifier
naive_model = GaussianNB()
naive_model.fit(X_train, y_train)


GaussianNB()

In [ ]:
#predict labels for test set
y_pred = naive_model.predict(X_test)

In [ ]:
#create comfusion matrix
confusion =  confusion_matrix(y_test,y_pred)

In [ ]:
#display confusion matrix
print("Confusion Matrix:")
print(confusion)

Confusion Matrix:
[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


Rows represent the true (actual) classes.

Columns represent the predicted classes.

Class 0: Setosa

Class 1: Versicolor

Class 2: Virginica


[[ 9  0  0]   <- True Setosa instances

 [ 0 10  1]   <- True Versicolor instances

 [ 0  0 10]]  <- True Virginica instances


 The diagonal elements represent correct predictions (True Positives).

The off-diagonal elements represent misclassifications (False Positives and False Negatives).

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Compute metrics
accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred, average='macro')  # Using 'macro' for multi-class
recall = recall_score(y_test, y_pred, average='macro')        # Using 'macro' for multi-class
f1 = f1_score(y_test, y_pred, average='macro')                # Using 'macro' for multi-class

#macro average is a method of calculating performance metrics in multi-class classification problems, where you have more than two classes

# Print metrics
print(f"\n\nAccuracy is: {accuracy:.4f}")
print(f"\nError Rate: {error_rate:.4f}")
print(f"\nPrecision: {precision:.4f}")
print(f"\nRecall: {recall:.4f}")
print(f"\nF1 Score: {f1:.4f}")


Confusion Matrix:
[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


Accuracy is: 1.0000

Error Rate: 0.0000

Precision: 1.0000

Recall: 1.0000

F1 Score: 1.0000


alternate ways of evaluating metric

In [ ]:
#extract values from confusion matrix
TN = confusion[0,0]
FP = confusion[0,1]
FN = confusion[1,0]
TP = confusion[1,1]

In [ ]:
#compute accuracy
accuracy = (TP + TN) / (TP + TN + FP + FN)
print("Accuracy is :", accuracy)

Accuracy is : 1.0


In [ ]:
#compute precision
precision = TP / (TP + FP) #positive predictions that are actually correct
print("Precision is :", precision)

Precision is : 1.0


In [ ]:
#display the recall
recall = TP / (TP + FN)   #actual  positive that are correctly identifies by model
print("Recall is :", recall)

Recall is : 1.0
